import os
import datetime
import numpy as np


def read(filename='in.conf'):
    """Read GOMC parameter file
    """
    from __init__ import GOMC
    gomc = GOMC()
    with open(filename, 'r') as f:
        for line in f:
            if line[0].isalpha():
                # ignoring all lines that do not start with a letter
                splitted = line.split()
                gomc.set(splitted[0], *tuple(splitted[1:]))
    return gomc


def write(self, filename='in.conf', verbose=True):
    """Write GOMC parameter file
    """
    now = datetime.datetime.now()
    filepath = os.path.join(self.wd, filename)

    with open(filepath, 'w') as f:

        f.write("#" * 30 + "\n")
        f.write("## Written by GOMC-wrapper \n")
        f.write(f"## DATE: {now:%Y-%m-%d %H:%M:%S}\n")
        f.write("#" * 30 + "\n")

        f.write("\n" + "#" * 76 + "\n")
        f.write("# " + "=" * 8 + "-" * 25 + " INPUT " + "-" * 25 + "=" * 8)
        f.write("\n" + "#" * 76 + "\n")

        for key, obj in self.parameters.items():
            if key == "ParaTypeCHARMM" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# FORCEFIELD")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "Coordinates" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# INPUT FILES")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "GEMC":
                f.write("\n" + "#" * 76 + "\n")
                f.write("# " + "=" * 8 + "-" * 25 + " SYSTEM " + "-" * 25 + "=" * 8)
                f.write("\n" + "#" * 76 + "\n")

                if verbose:
                    f.write("\n" + "#" * 36 + "\n")
                    f.write("# GEMC TYPE")
                    f.write("\n" + "#" * 36 + "\n")

            elif key == "Pressure" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# SIMULATION CONDITION")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "ElectroStatic" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# ELECTROSTATIC")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "PressureCalc" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# PRESSURE CALCULATION")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "RunSteps" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# STEPS")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "DisFreq" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# MOVE FREQUENCY")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "CellBasisVector1" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# BOX DIMENSIONS #, X, Y, Z")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "CBMC_First" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# CBMC TRIALS")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "OutputName":
                f.write("\n" + "#" * 76 + "\n")
                f.write("# " + "=" * 8 + "-" * 25 + " OUTPUT " + "-" * 25 + "=" * 8)
                f.write("\n" + "#" * 76 + "\n")

                if verbose:
                    f.write("\n" + "#" * 36 + "\n")
                    f.write("# statistics filename add")
                    f.write("\n" + "#" * 36 + "\n")

            elif key == "CoordinatesFreq" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# enable, frequency")
                f.write("\n" + "#" * 36 + "\n")

            elif key == "OutEnergy" and verbose:
                f.write("\n" + "#" * 36 + "\n")
                f.write("# enable: blk avg., fluct.")
                f.write("\n" + "#" * 36 + "\n")

            if len(obj.values) > 0:
                f.write(key.ljust(16) + " \t")
                f.write(str(obj) + "\n")


def write_topology(mol='OHHM',
                   mass={'O': 15.9994, 'H': 1.0079, 'M': 0.0},
                   charge={'O': 0.0, 'H': 0.5564, 'M': -1.1128},
                   bonds=['OH', 'OM'], filename="topology.inp"):
    """Write topology file
    """
    atoms = list(mol)
    atoms_unique = np.unique(atoms)

    with open(filename, 'w') as f:
        f.write("* Custom top file generated by GOMC-wrapper\n\n")

        for i, atom in enumerate(atoms_unique):
            f.write(f"MASS    {i+1}  {atom}    {mass[atom]:>7}  {atom} !\n")

        f.write("\nDEFA FIRS none LAST none\n")
        f.write("AUTOGENERATE ANGLES DIHEDRALS\n")

        f.write("\nRESI TIP4                  0.0000 !\n")
        f.write("GROUP\n")

        for atom in atoms:
            f.write(f"ATOM {atom}     {atom}     {charge[atom]} !\n")

        f.write("BOND ")
        for i in range(len(atoms)):
            for j in range(i+1):
                if 1 > 2:
                    print("Let's finish this tomorrow")


def psfgen(coordinates="coord.pdb", topology="topology.inp"):
    """Generate PSF file
    """
    pass


if __name__ == "__main__":
    gomc = read("/home/evenmn/tip4p-vapor/src/gemc_gomc/in.conf")
    gomc.write("in.conf", verbose=False)
